version: '3.8'

services:
  db:
    image: postgres:17
    container_name: db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    depends_on:
      - db
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

    command: >
      start-dev
      --http-port=8081
      --import-realm

    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
    ports:
      - "8081:8081"

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    depends_on:
      - keycloak
    ports:
      - "8082:8080"
    environment:
      KEYCLOAK_HOST: keycloak
      KEYCLOAK_PORT: 8081
      KEYCLOAK_REALM: rrom-realm
      KEYCLOAK_CLIENT_ID: auth-client
      KEYCLOAK_CLIENT_SECRET: secret123

      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/postgres"
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin


  task-service:
    build:
      context: ./task-service
      dockerfile: Dockerfile
    container_name: task-service
    depends_on:
      keycloak:
        condition: service_started
      auth-service:
        condition: service_started



    ports:
      - "8083:8080"
    environment:
      KEYCLOAK_HOST: keycloak
      KEYCLOAK_PORT: 8081
      KEYCLOAK_REALM: rrom-realm
      REALM_PATH: "http://keycloak:8081/realms/rrom-realm"



      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/postgres"
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin

volumes:
  db-data:
